- name: Install and configure Nginx
  hosts: webservers
  
  tasks:
    - name : installation nginx
      apt :
        name : nginx
        state : present
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom homepage
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart nginx
  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted



    